// <auto-generated />
using System;
using GazaRealEstatePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GazaRealEstatePortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731121204_SeedRealData")]
    partial class SeedRealData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GazaRealEstatePortal.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<string>("CityAreaCamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 150m,
                            Bathrooms = 2,
                            CityAreaCamp = "الرمال",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "شقة سكنية تشطيب سوبر ديلوكس في الرمال.",
                            DetailedAddress = "شارع عمر المختار",
                            Features = "موقف سيارة, مصعد",
                            Floor = "2",
                            Governorate = "غزة",
                            OperationType = "Sale",
                            Price = 120000m,
                            PropertyType = "Apartment",
                            Rooms = 3,
                            Status = "Approved",
                            Title = "شقة سكنية فاخرة",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        },
                        new
                        {
                            Id = 2,
                            Area = 300m,
                            Bathrooms = 3,
                            CityAreaCamp = "البلد",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "فيلا حديثة في خانيونس البلد بمساحة ممتازة.",
                            DetailedAddress = "وسط البلد",
                            Features = "حديقة, كراج",
                            Floor = "0",
                            Governorate = "خانيونس",
                            OperationType = "Rent",
                            Price = 400m,
                            PropertyType = "Villa",
                            Rooms = 5,
                            Status = "Approved",
                            Title = "فيلا حديثة التصميم",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        },
                        new
                        {
                            Id = 3,
                            Area = 1000m,
                            Bathrooms = 0,
                            CityAreaCamp = "بيت لاهيا",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "أرض زراعية خصبة في بيت لاهيا.",
                            DetailedAddress = "منطقة العطاطرة",
                            Features = "بئر ماء",
                            Floor = "0",
                            Governorate = "الشمال",
                            OperationType = "Sale",
                            Price = 50000m,
                            PropertyType = "Land",
                            Rooms = 0,
                            Status = "Approved",
                            Title = "أرض زراعية",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        },
                        new
                        {
                            Id = 4,
                            Area = 85m,
                            Bathrooms = 1,
                            CityAreaCamp = "النصر",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "مكتب تجاري جاهز للعمل في النصر.",
                            DetailedAddress = "شارع النصر",
                            Features = "تكييف, إنترنت",
                            Floor = "1",
                            Governorate = "غزة",
                            OperationType = "Rent",
                            Price = 1200m,
                            PropertyType = "Office",
                            Rooms = 2,
                            Status = "Approved",
                            Title = "مكتب تجاري مجهز",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        },
                        new
                        {
                            Id = 5,
                            Area = 200m,
                            Bathrooms = 2,
                            CityAreaCamp = "تل السلطان",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "منزل مستقل وواسع في تل السلطان.",
                            DetailedAddress = "غرب تل السلطان",
                            Features = "حوش, تهوية ممتازة",
                            Floor = "1",
                            Governorate = "رفح",
                            OperationType = "Sale",
                            Price = 85000m,
                            PropertyType = "House",
                            Rooms = 4,
                            Status = "Approved",
                            Title = "منزل مستقل",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        },
                        new
                        {
                            Id = 6,
                            Area = 130m,
                            Bathrooms = 1,
                            CityAreaCamp = "النصيرات",
                            ContactPhone = "0593617699",
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Description = "شقة عائلية مريحة في النصيرات.",
                            DetailedAddress = "المخيم الجديد",
                            Features = "قريبة من الخدمات",
                            Floor = "3",
                            Governorate = "الوسطى",
                            OperationType = "Sale",
                            Price = 60000m,
                            PropertyType = "Apartment",
                            Rooms = 3,
                            Status = "Approved",
                            Title = "شقة عائلية",
                            UpdatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WhatsAppNumber = "00970593617699"
                        });
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 1,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 2,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 3,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 4,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 5,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            PropertyId = 6,
                            UploadedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.PropertyReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyReviews");
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExternalProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gaza-realestate.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$Opgsk4F5QPn18MUikFvbf.phbT36mFqvL2t4mIko1P/lkeQu7xMrm",
                            PhoneNumber = "0590000000",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 14, 55, 9, 0, DateTimeKind.Utc),
                            Email = "sondosalaa687@gmail.com",
                            FullName = "Sondos Alaa Yassin",
                            IsActive = true,
                            PasswordHash = "$2a$11$EbXyQBCIEPmReCYun1S4e.E7hs9PNHy1stk841TCweJ4hCK9g37mG",
                            PhoneNumber = "0593617699",
                            Role = "RegisteredUser"
                        });
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.Property", b =>
                {
                    b.HasOne("GazaRealEstatePortal.Models.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.PropertyImage", b =>
                {
                    b.HasOne("GazaRealEstatePortal.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.PropertyReview", b =>
                {
                    b.HasOne("GazaRealEstatePortal.Models.User", "Admin")
                        .WithMany("ReviewsMade")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GazaRealEstatePortal.Models.Property", "Property")
                        .WithOne("Review")
                        .HasForeignKey("GazaRealEstatePortal.Models.PropertyReview", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("GazaRealEstatePortal.Models.User", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("ReviewsMade");
                });
#pragma warning restore 612, 618
        }
    }
}
